import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { ContactForm } from "@/components/EmailForm";
import { MainPage } from "@/components/MainPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"
        ></script>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `emailjs.init('-a7fLrpzWxm2Mhz4K');`,
          }}
        />
      </Head>
      <main>
        <MainPage />
      </main>
    </>
  );
}
